# Generated by Django 5.2.1 on 2025-06-01 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deceased',
            fields=[
                ('deceased_id', models.AutoField(primary_key=True, serialize=False)),
                ('deceased_name', models.CharField(max_length=30)),
                ('deceased_dob', models.DateField()),
                ('deceased_dod', models.DateField()),
                ('deceased_img', models.ImageField(upload_to='')),
                ('deceased_add', models.TextField(max_length=100)),
                ('deseased_phoneno', models.IntegerField()),
                ('deseased_info', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='graves',
            fields=[
                ('grave_id', models.AutoField(primary_key=True, serialize=False)),
                ('grave_no', models.IntegerField()),
                ('status', models.CharField(choices=[('buried', 'buried'), ('reserved', 'reserved'), ('available', 'available')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='graveyard',
            fields=[
                ('graveyard_id', models.AutoField(primary_key=True, serialize=False)),
                ('graveyard_name', models.CharField(max_length=30)),
                ('graveyard_add', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='digital_memorial',
            fields=[
                ('memorial_id', models.AutoField(primary_key=True, serialize=False)),
                ('memorial_name', models.CharField(max_length=30)),
                ('memorial_message', models.TextField(max_length=200)),
                ('memorial_img', models.ImageField(upload_to='')),
                ('memorial_deceased_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.deceased')),
            ],
        ),
        migrations.AddField(
            model_name='deceased',
            name='grave_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graves'),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('booking_reserver_name', models.CharField(max_length=20)),
                ('booking_reserver_contact', models.IntegerField()),
                ('booking_reservation_date', models.DateField()),
                ('booking_status', models.CharField(choices=[('pending', 'pending'), ('reserved', 'reserved')], max_length=10)),
                ('booking_grave_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graves')),
            ],
        ),
        migrations.AddField(
            model_name='graves',
            name='graveyard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graveyard'),
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_add', models.TextField(max_length=100)),
                ('employee_no', models.IntegerField()),
                ('employee_work_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graveyard')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
                ('graveyard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graveyard')),
            ],
        ),
        migrations.CreateModel(
            name='maintain',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_date', models.DateField()),
                ('main_completebydate', models.DateField()),
                ('main_status', models.CharField(choices=[('pending', 'pending'), ('reserved', 'reserved')], max_length=10)),
                ('main_desc', models.TextField(max_length=200)),
                ('main_grave_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graves')),
            ],
        ),
        migrations.CreateModel(
            name='performed_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.TimeField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.employee')),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.maintain')),
            ],
        ),
    ]
