# Generated by Django 5.2.1 on 2025-06-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_deseased_info_deceased_deceased_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='graveyardinfo',
            fields=[
                ('graveyard_id', models.AutoField(primary_key=True, serialize=False)),
                ('graveyard_name', models.CharField(max_length=30)),
                ('graveyard_add', models.CharField(max_length=50)),
                ('graveyard_plots', models.IntegerField()),
                ('graveyard_phoneno', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='graveyard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graveyardinfo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_work_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graveyardinfo'),
        ),
        migrations.AlterField(
            model_name='graves',
            name='graveyard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graveyardinfo'),
        ),
        migrations.DeleteModel(
            name='graveyard',
        ),
    ]
