# Generated by Django 5.2.1 on 2025-06-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_gravesplots_graveyardinfo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='graveyardinfo',
            new_name='graveyard1',
        ),
    ]
