# Generated by Django 5.2.1 on 2025-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_graveplots_grave_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintain',
            name='main_contact',
            field=models.CharField(default='preetham', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintain',
            name='main_name',
            field=models.CharField(default='preetham', max_length=20),
            preserve_default=False,
        ),
    ]
