# Generated by Django 5.2.1 on 2025-06-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_performed_by_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain',
            name='main_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
