# Generated by Django 5.2.1 on 2025-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_remove_deceased_deceased_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graveplots',
            name='grave_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='graveyard',
            name='graveyard_phoneno',
            field=models.CharField(max_length=15),
        ),
    ]
