# Generated by Django 5.2.1 on 2025-06-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deceased',
            old_name='deseased_info',
            new_name='deceased_info',
        ),
        migrations.RenameField(
            model_name='deceased',
            old_name='deseased_phoneno',
            new_name='deceased_phoneno',
        ),
    ]
