# Generated by Django 5.2.1 on 2025-06-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_graveyardinfo_alter_contact_graveyard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='deceased_phoneno',
            field=models.CharField(max_length=15),
        ),
    ]
