# Generated by Django 5.2.1 on 2025-06-03 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_graveyard_alter_contact_graveyard_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='graveplots',
            fields=[
                ('grave_id', models.AutoField(primary_key=True, serialize=False)),
                ('grave_no', models.IntegerField()),
                ('status', models.CharField(choices=[('buried', 'buried'), ('reserved', 'reserved'), ('available', 'available')], max_length=10)),
                ('grave_column', models.IntegerField()),
                ('grave_row', models.IntegerField()),
                ('graveyard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graveyard')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_grave_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graveplots'),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='grave_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graveplots'),
        ),
        migrations.AlterField(
            model_name='maintain',
            name='main_grave_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.graveplots'),
        ),
        migrations.DeleteModel(
            name='graves',
        ),
    ]
