# Generated by Django 5.2.1 on 2025-06-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_maintain_main_contact_maintain_main_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintain',
            old_name='main_desc',
            new_name='main_disc',
        ),
        migrations.AlterField(
            model_name='maintain',
            name='main_date',
            field=models.DateField(auto_now=True),
        ),
    ]
