# Generated by Django 5.2.1 on 2025-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_rename_main_desc_maintain_main_disc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain',
            name='main_status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], max_length=10),
        ),
    ]
