# Generated by Django 5.2.1 on 2025-06-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_performed_by_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_no',
            field=models.CharField(max_length=15),
        ),
    ]
