# Generated by Django 5.2.1 on 2025-06-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_employee_employee_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_reservation_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_proof',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
