# Generated by Django 5.2.1 on 2025-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_remove_booking_booking_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reserver_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='graveplots',
            name='grave_row',
            field=models.IntegerField(),
        ),
    ]
