# Generated by Django 5.2.1 on 2025-06-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performed_by',
            name='completed_at',
            field=models.DateField(),
        ),
    ]
