# Generated by Django 5.2.1 on 2025-06-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_maintain_main_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deceased',
            name='deceased_img',
        ),
        migrations.RemoveField(
            model_name='digital_memorial',
            name='memorial_img',
        ),
    ]
